name: 'Setup'
description: 'Install dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y librust-gdk4-sys-dev \
          libglib2.0-dev libgtk-layer-shell-dev libgtk-layer-shell0 gir1.2-gtklayershell-0.1 \
          libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools python3 valac \
          git cmake gcc meson ninja-build
      shell: bash
    - name: Install gtk4 layer shell
      run: |
        git clone https://github.com/wmww/gtk4-layer-shell
        cd gtk4-layer-shell
        meson setup -Dexamples=true -Ddocs=true -Dtests=true build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig
      shell: bash