image_size=64
columns=4
orientation="Vertical"
row_box_orientation="Vertical"
content_halign="Center"
height="105%"
width="100%"
valign="Start"
blurred_background=false
line_max_chars=32
key_detection_type="Code"
term="kitty -e"
