image_size = 0
columns = 999
allow_images = false
orientation = "Horizontal"
row_box_orientation = "Horizontal"
content_halign = "Start"
width = "100%"
hide_scroll = true
location = ["Top"]
lines = 1
